server:
  port: ${SERVER_PORT:8080}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: health, info, metrics

spring:
  application:
    name: Color-Service

app:
  color: ${APP_COLOR:Red}
