version: '3'
services:
  gateway:
    image: asakchris/service-mesh-gateway:1.0.0-SNAPSHOT
    environment:
      - COLOR_SERVICE_URL=http://color-red:8080
    ports:
      - "8080:8080"
      - "8081:8081"
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8081/actuator/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
  color-red:
    image: asakchris/service-mesh-color:1.0.0-SNAPSHOT
    environment:
      - APP_COLOR=Red
    ports:
      - "8000:8080"
      - "8001:8081"
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8081/actuator/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
  color-green:
    image: asakchris/service-mesh-color:1.0.0-SNAPSHOT
    environment:
      - APP_COLOR=Green
    ports:
      - "8002:8080"
      - "8003:8081"
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8081/actuator/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
  color-blue:
    image: asakchris/service-mesh-color:1.0.0-SNAPSHOT
    environment:
      - APP_COLOR=Blue
    ports:
      - "8004:8080"
      - "8005:8081"
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8081/actuator/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
