version: '3'
services:
  color-red:
    image: asakchris/service-mesh-color:1.0.0-SNAPSHOT
    environment:
      - APP_COLOR=Red
    ports:
      - "8000:8080"
      #- "8001:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
  color-green:
    image: asakchris/service-mesh-color:1.0.0-SNAPSHOT
    environment:
      - APP_COLOR=Green
    ports:
      - "8002:8080"
      #- "8003:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
  color-blue:
    image: asakchris/service-mesh-color:1.0.0-SNAPSHOT
    environment:
      - APP_COLOR=Blue
    ports:
      - "8004:8080"
      #- "8005:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
  random-number:
    image: asakchris/service-mesh-random:1.0.0-SNAPSHOT
    ports:
      - "8010:8080"
      #- "8011:8081"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 5
