server:
  port: ${APP_SERVER_PORT:8080}

management:
  server:
    #port: ${APP_MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: health, info, metrics

spring:
  application:
    name: Random-Service
