AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates app mesh
Parameters:
  Environment:
    Type: String
    Description: Environment Name (DEV)
    AllowedValues: [ 'DEV' ]
  Platform:
    Type: String
    Default: 'AM'
    Description: Platform Name
Resources:
  Mesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Sub '${Environment}-${Platform}-MESH'
Outputs:
  MeshArn:
    Description: Mesh Arn
    Value: !Ref Mesh
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'MeshArn' ] ]
  MeshName:
    Description: Mesh Arn
    Value: !GetAtt 'Mesh.MeshName'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'MeshName' ] ]
