AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates gateway services task definition and service
Parameters:
  Environment:
    Type: String
    Description: Environment Name (DEV)
    AllowedValues: [ 'DEV' ]
  Platform:
    Type: String
    Default: 'AM'
    Description: Platform Name
  AppName:
    Type: String
    Default: 'GW'
    Description: Application Name
  ContainerPort:
    Type: Number
    Description: Port number to use for applications
    Default: 9080
  NlbStackName:
    Type: String
    Description: Name of the stack which is used to create NLB and Target Groups
  PrivateNamespaceStackName:
    Type: String
    Description: Name of the stack which is used to create Private Namespace
  RoleStackName:
    Type: String
    Description: Name of the stack which is used to create Roles
  EcsClusterStackName:
    Type: String
    Description: Name of the stack which is used to create ECS cluster
  VpcStackName:
    Type: String
    Description: Name of the stack which is used to create VPC and Subnets
  SecurityGroupStackName:
    Type: String
    Description: Name of the stack used to create security group
  AppMeshStackName:
    Type: String
    Description: Name of the stack used to create app mesh
  RedColorEcsServiceStackName:
    Type: String
    Description: Name of the stack used to create Red Color ECS Service
  RandomNumberEcsServiceStackName:
    Type: String
    Description: Name of the stack used to create Random Number ECS Service
Resources:
  # Cloud watch log group to which container send logs
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ECS/${Environment}/${Platform}/${AppName}'
      RetentionInDays: 1

  # Service discovery for Gateway service, DnsConfig property specifies the DNS records that are automatically created
  # in Amazon Route 53 when your Amazon ECS task is registered with the service discovery service
  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Discovery Service for Gateway service
      Name: gateway
      DnsConfig:
        NamespaceId:
          Fn::ImportValue: !Join [ ':', [ !Ref 'PrivateNamespaceStackName', 'ServiceDiscoveryPrivateNamespaceId' ] ]
        #RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig:
        FailureThreshold: 1

  VirtualGateway:
    Type: AWS::AppMesh::VirtualGateway
    Properties:
      MeshName:
        Fn::ImportValue: !Join [ ':', [ !Ref 'AppMeshStackName', 'MeshName' ] ]
      VirtualGatewayName: gateway-vg
      Spec:
        # The listeners that the mesh endpoint is expected to receive inbound traffic from
        Listeners:
          - PortMapping:
              Port: !Ref ContainerPort
              Protocol: http

  # The task definition. This is a simple metadata description of what container to run,
  # and what resource requirements it has.
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Environment}-${Platform}-${AppName}-TD-01'
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue: !Join [ ':', [ !Ref 'RoleStackName', 'ECSTaskExecutionRoleArn' ] ]
      TaskRoleArn:
        Fn::ImportValue: !Join [ ':', [ !Ref 'RoleStackName', 'ECSTaskRoleArn' ] ]
      ContainerDefinitions:
        - Name: !Sub '${Environment}-${Platform}-${AppName}-ENVOY'
          Image: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.15.1.0-prod
          Essential: true
          #User: 1337
          DependsOn:
            - ContainerName: !Sub '${Environment}-${Platform}-${AppName}-XRAY'
              Condition: START
          PortMappings:
            - ContainerPort: 9901
              Protocol: 'tcp'
            - ContainerPort: !Ref ContainerPort
              Protocol: 'tcp'
          Ulimits:
            - Name: nofile
              SoftLimit: 15000
              HardLimit: 15000
          HealthCheck:
            Command:
              - 'CMD-SHELL'
              - 'curl -s http://localhost:9901/server_info | grep state | grep -q LIVE'
            Interval: 5
            Retries: 3
            StartPeriod: 60
            Timeout: 2
          Environment:
            - Name: APPMESH_RESOURCE_ARN
              Value: !Ref VirtualGateway
            - Name: ENVOY_LOG_LEVEL
              Value: debug
            - Name: ENABLE_ENVOY_XRAY_TRACING
              Value: 1
            #- Name: APPMESH_VIRTUAL_NODE_NAME
              #Value: !Sub 'mesh/${Environment}-${Platform}-MESH/virtualGateway/gateway-vg'
            - Name: ENABLE_ENVOY_STATS_TAGS
              Value: 1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: envoy
        - Name: !Sub '${Environment}-${Platform}-${AppName}-XRAY'
          Image: amazon/aws-xray-daemon
          Essential: true
          User: 1337
          PortMappings:
            - ContainerPort: 2000
              Protocol: udp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: xray

  # Service is a resource which allows to run multiple copies of a type of task, and gather up their logs and metrics,
  # as well as monitor the number of running tasks and replace any that have crashed
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${Environment}-${Platform}-${AppName}-SERVICE-01'
      Cluster:
        Fn::ImportValue: !Join [ ':', [ !Ref 'EcsClusterStackName', 'EcsClusterName' ] ]
      LaunchType: FARGATE
      PlatformVersion: 1.4.0
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      DesiredCount: 1
      TaskDefinition: !Ref ECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Join [ ':', [ !Ref 'SecurityGroupStackName', 'ContainerSecurityGroupId' ] ]
          Subnets:
            - Fn::ImportValue: !Join [ ':', [ !Ref 'VpcStackName', 'PrivateSubnetOne' ] ]
            - Fn::ImportValue: !Join [ ':', [ !Ref 'VpcStackName', 'PrivateSubnetTwo' ] ]
      LoadBalancers:
        - ContainerName: !Sub '${Environment}-${Platform}-${AppName}-ENVOY'
          ContainerPort: !Ref ContainerPort
          TargetGroupArn:
            Fn::ImportValue: !Join [ ':', [ !Ref 'NlbStackName', 'TargetGroupArn' ] ]
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn

  ColorGatewayRoute:
    Type: AWS::AppMesh::GatewayRoute
    Properties:
      GatewayRouteName: color-route
      MeshName:
        Fn::ImportValue: !Join [ ':', [ !Ref 'AppMeshStackName', 'MeshName' ] ]
      VirtualGatewayName: !GetAtt VirtualGateway.VirtualGatewayName
      Spec:
        HttpRoute:
          Match:
            Prefix: /color
          Action:
            Target:
              VirtualService:
                VirtualServiceName:
                  Fn::ImportValue: !Join [ ':', [ !Ref 'RedColorEcsServiceStackName', 'VirtualServiceName' ] ]
  RandomNumberGatewayRoute:
    Type: AWS::AppMesh::GatewayRoute
    Properties:
      GatewayRouteName: random-number-route
      MeshName:
        Fn::ImportValue: !Join [ ':', [ !Ref 'AppMeshStackName', 'MeshName' ] ]
      VirtualGatewayName: !GetAtt VirtualGateway.VirtualGatewayName
      Spec:
        HttpRoute:
          Match:
            Prefix: /random-number
          Action:
            Target:
              VirtualService:
                VirtualServiceName:
                  Fn::ImportValue: !Join [ ':', [ !Ref 'RandomNumberEcsServiceStackName', 'VirtualServiceName' ] ]
