AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates all required security groups
Parameters:
  Environment:
    Type: String
    Description: Environment Name (DEV)
    AllowedValues: [ 'DEV' ]
  Platform:
    Type: String
    Default: 'AM'
    Description: Platform Name
  VpcStackName:
    Type: String
    Description: Name of the stack which is used to create VPC and Subnets
Resources:
  # A security group for the containers
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: security group for the containers
      VpcId:
        Fn::ImportValue: !Join [ ':', [ !Ref 'VpcStackName', 'VPCId' ] ]
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp:
            Fn::ImportValue: !Join [ ':', [ !Ref 'VpcStackName', 'VPCCidrBlock' ] ]
          Description: Ingress from the VPC
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${Platform}-CONTAINER-SG-01'
Outputs:
  ContainerSecurityGroup:
    Description: Container Security Group Id
    Value: !Ref 'ContainerSecurityGroup'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'ContainerSecurityGroupId' ] ]
